---
- hosts: localhost
  tasks:
  - name: Creamos una nueva VPC
    ec2_vpc_net:
      cidr_block: 172.22.0.0/16
      region: us-east-1
      name: MiNuevaVPC
    register: ec2_vpc_net_result
  - name: Creamos una subred para la VPC anterior
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ec2_vpc_net_result.vpc.id}}"
      cidr: 172.22.1.0/24
      resource_tags:
        Name: MiNuevaVPC Subnet
    register: subnet
  - name: Creamos un internet gateway para asociar al VPC
    ec2_vpc_igw:
      vpc_id: "{{ec2_vpc_net_result.vpc.id}}"
      state: present
      region: us-east-1
    register: igw
  - name: Debugueamos la salida de creacion de VPC
    debug:
      msg:
      - "vpc id: {{ec2_vpc_net_result.vpc.id}}   igw: {{igw}}  subnet: {{subnet}}"
  - name: Crear grupo de seguridad con HTTPS, HTTP y SSH
    ec2_group:
      name: MiNuevaVPC_GrupoSeguridad
      vpc_id: "{{ec2_vpc_net_result.vpc.id}}"
      description: Grupo de seguridad con puertos abiertos 443,80, 22
      region: us-east-1
      rules:
        - proto: tcp
          ports:
          - 443
          - 80
          - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: Acepto todo el trafico de internet
    register: group
  - name: Creamos nuestro servidor
    ec2:
      region: us-east-1
      instance_type: t2.micro
      image: ami-0c2b8ca1dad447f8a
      wait: yes
      wait_timeout: 500
      volumes:
        - device_name: /dev/xvda
          volume_type: gp2
          volume_size: 8
      vpc_subnet_id: "{{subnet.subnet.id}}"
      assign_public_ip: yes
      key_name: clase7-claves
      group_id: "{{group.group_id}}"
    register: info
  - name: DNS Publico de nuestro servidor
    debug:
      msg: 
      - " {{info.instances[0].public_dns_name}} {{info.instances[0].public_ip}}"