---
- hosts: localhost
  tasks:
  - name: Crear grupo de seguridad con HTTPS, HTTP y SSH
    ec2_group:
      name: MiNuevaVPC_GrupoSeguridad
      vpc_id: vpc-03875c1942fae6e25
      description: Grupo de seguridad con puertos abiertos 443,80, 22
      region: us-east-1
      rules:
        - proto: tcp
          ports:
          - 443
          - 80
          - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: Acepto todo el trafico de internet
    register: group
  - name: Creamos nuestro servidor
    ec2:
      region: us-east-1
      instance_type: t2.micro
      image: ami-0c2b8ca1dad447f8a
      wait: yes
      wait_timeout: 500
      volumes:
        - device_name: /dev/xvda
          volume_type: gp2
          volume_size: 8
      vpc_subnet_id: subnet-0bf23c9d6db64d380
      assign_public_ip: yes
      key_name: clase7-claves
      group_id: "{{group.group_id}}"
    register: info
  - name: DNS Publico de nuestro servidor
    debug:
      msg: 
      - " {{info.instances[0].public_dns_name}} {{info.instances[0].public_ip}}"

